// organize-imports-ignore
import { VerticalNavigation } from '@/predefined/components/Navigations';
import type { Metadata } from 'next';
// Element must be imported before initialization
import Element from '@/renderer/strategies/Element';
import './globals.css';
import { initComponent } from '@/renderer/helpers/init';
import { PrepareRenderer } from '@/renderer/PrepareRenderer';

export const metadata: Metadata = {
  title: 'UniSoft',
  description: 'Generated by create next app',
};

export default async function RootLayout({
                                           children,
                                         }: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
    <body>
      <PrepareRenderer component={await initComponent(VerticalNavigation)} key={"layout"} />
    {children}
    </body>
    </html>
  );
}
