import './globals.css';
import type { Metadata } from 'next';
import Logo from '@/public/kgb.png';
import { PrepareRenderer } from '@/renderer/PrepareRenderer';
import { generateComponentForRendering } from '@/renderer/helpers/initializors';
import {VerticalNavigation} from "@/predefined/components/Navigations";

export const metadata: Metadata = {
  title: 'UniSoft',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const Navi = VerticalNavigation({ Logo });
  await generateComponentForRendering(Navi);

  return (
    <html lang='en'>
      <body>
        <PrepareRenderer component={Navi} key={Navi.uuid} fromClient={false} />
        {children}
      </body>
    </html>
  );
}
