import "./globals.css";
import type { Metadata } from "next";
import {NavWithLogo} from "@/predefined/components/Navigations/NavWithLogo";
import {PrepareRenderer} from "@/renderer/PrepareRenderer";

export const metadata: Metadata = {
  title: "UniSoft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>

      <PrepareRenderer component={NavWithLogo} index={23123} key={`layout`} generateProps={true} />
      {children}</body>
    </html>
  );
}
